file = open('Beyond the Wall of Sleep.txt', encoding="utf8")
Beyond= file.read()
file2 = open('Pride and Prejudice.txt', encoding="utf8")
Pride= file2.read()
Beyond=Beyond.lower().split()
Pride=Pride.lower().split()
intersection = set(Beyond) & set(Pride)
print(intersection)
file.close()
file2.close()